version: '3'
services:
  linkapi:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    ports:
      - "3000:3000"
    build: ./docker
    volumes:
      - .:/usr/src/app/
